/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
  

import com.lowagie.text.Document;
import com.lowagie.text.PageSize;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.AWTException;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Robot;
import java.awt.Shape;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.print.PrinterException;
import java.io.FileOutputStream;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Action;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.KeyStroke;




/**
 *
 * @author nico
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        jLabel5.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        
        JTextField function=new JTextField(8);   
function.addActionListener(new ActionListener(){

                public void actionPerformed(ActionEvent e){

                        //statements!!!

                }

           
        });

    }
    public String[][] prestamo;
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txbMonto = new javax.swing.JTextField();
        txbCuotas = new javax.swing.JTextField();
        txbInteres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbMetodo = new javax.swing.JComboBox();
        cmbFormadepago = new javax.swing.JComboBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txbMontoPorPagos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txbMontoFinal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txbTotal = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Terminos del prestamo:");

        jLabel2.setText("Monto $:");

        jLabel3.setText("Cantidad de Cuotas:");

        jLabel4.setText("Interes Mensual %:");

        txbMonto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txbMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbMontoActionPerformed(evt);
            }
        });
        txbMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txbMontoFocusGained(evt);
            }
        });
        txbMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txbMontoKeyPressed(evt);
            }
        });

        txbCuotas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txbCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbCuotasActionPerformed(evt);
            }
        });

        txbInteres.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txbInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbInteresActionPerformed(evt);
            }
        });

        jLabel6.setText("Metodo:");

        jLabel7.setText("Forma de Pago:");

        jLabel8.setText("Fecha de inicio:");

        cmbMetodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Lineal - Capitalizado", "Solo interes" }));

        cmbFormadepago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Semanal", "Mensual", "Anual" }));

        jDateChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDateChooser1MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cuota", "Pago", "Vence El:", "Capital", "Interes"
            }
        ));
        jTable1.setEnabled(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setText("Cuotas:");

        jLabel10.setText(" ---------------------------------------------------------------------------------------------------------------------------------------------");

        jLabel11.setText("Monto Prestamo $:");

        txbMontoPorPagos.setEditable(false);
        txbMontoPorPagos.setBackground(new java.awt.Color(200, 241, 240));
        txbMontoPorPagos.setCaretColor(new java.awt.Color(200, 0, 0));
        txbMontoPorPagos.setSelectionColor(new java.awt.Color(200, 100, 100));

        jLabel12.setText("Monto por Pagos $:");

        txbMontoFinal.setEditable(false);
        txbMontoFinal.setBackground(new java.awt.Color(200, 241, 240));
        txbMontoFinal.setCaretColor(new java.awt.Color(2, 2, 2));
        txbMontoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbMontoFinalActionPerformed(evt);
            }
        });

        jLabel13.setText("Total a Pagar $:");

        txbTotal.setEditable(false);
        txbTotal.setBackground(new java.awt.Color(200, 241, 240));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        jLabel5.setText("Monto Pago final: $");

        jLabel15.setText("Total Interes: $");

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Document-New-icon1.png"))); // NOI18N

        jMenuItem3.setText("Nuevo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/export.png"))); // NOI18N

        jMenuItem1.setText("Imprimir y/o Exportar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/info.png"))); // NOI18N

        jMenuItem2.setText("Info");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/power-512.png"))); // NOI18N

        jMenuItem4.setText("Salir");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txbInteres)
                            .addComponent(txbCuotas)
                            .addComponent(txbMonto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(cmbFormadepago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCalcular)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(66, 66, 66)
                                    .addComponent(cmbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(224, 224, 224))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txbMontoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txbMontoPorPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel14))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(253, 253, 253)
                                .addComponent(jLabel16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15)
                                .addGap(165, 165, 165))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCalcular))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txbMonto)
                            .addComponent(jLabel6)
                            .addComponent(cmbMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txbCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(cmbFormadepago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txbInteres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txbMontoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(txbMontoPorPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)
                        .addComponent(txbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txbCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbCuotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbCuotasActionPerformed

    private void txbMontoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbMontoFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbMontoFinalActionPerformed

    private void txbMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbMontoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txbMontoActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed

        int forma = cmbFormadepago.getSelectedIndex();

        int pago = cmbMetodo.getSelectedIndex();
        
       

        /*if (forma == 0) {
         JOptionPane.showMessageDialog(this, "Seleccione una forma de pago ", "ERROR", 3);
         } else if (forma == 1) {
         jDateChooser1.getCalendar().add(Calendar.DAY_OF_YEAR, 1);

         } else if (forma == 2) {
         jDateChooser1.getCalendar().add(Calendar.WEEK_OF_YEAR, 1);
         } else if (forma == 3) {
         jDateChooser1.getCalendar().add(Calendar.MONTH, 1);

         } else if (forma == 4) {
         jDateChooser1.getCalendar().add(Calendar.YEAR, 1);
         }

         String fecha = "" + jDateChooser1.getCalendar().get(Calendar.DAY_OF_MONTH) + "/"
         + (jDateChooser1.getCalendar().get(Calendar.MONTH) + 1) + "/"
         + jDateChooser1.getCalendar().get(Calendar.YEAR);
         dia}
         mes
         año
         getearvariablede tipo de prestamo
         poner en el for if es diario dia+1, si mes +1
        
         LINEAL:
         monto del capital:
        
         lineal == txbCuotas/txbMonto
        
        
        
         */
        // TODO add your handling code here:
        //int cuotas = Integer.parseInt(txbCuotas.getText());
        //float monto = Float.parseFloat(txbMonto.getText());
        //
        //  Object[][]
        Calendar fechaCal = jDateChooser1.getCalendar();

        String[] NuevoPrestamo = {txbCuotas.getText(), null, null, null, null};
        DefaultTableModel modelo = (DefaultTableModel) this.jTable1.getModel();
        modelo.setRowCount(0);
        String fecha = "";
        float interes = 0;
        int capital = 0;
        int intcap = 0;
        int acuinter= 0;
        int total = 0;
        int capital1 = 0; 
        int acupagos = 0;
        int acupagos1 = 0;
        int acupagos2 = 0;
        int acupagos3 = 0;
        int asd = 0;

        //interes = Integer.parseInt(txbInteres.getText())+(Integer.parseInt(txbCuotas.getText())/Integer.parseInt(txbMonto.getText()));
         try {
 
        for (int i = 1; i <= Integer.parseInt(this.txbCuotas.getText()); i++) {
                                fecha = fechaToString(fechaCal);

            if (pago == 2) {
                

                if (forma == 0) {
                    JOptionPane.showMessageDialog(this, "Seleccione una forma de pago ", "ERROR", 3);
                    return;
               
                } else if (forma == 1) {
                    fechaCal.add(Calendar.WEEK_OF_YEAR, 1);
                    acuinter = acuinter + (int) interes;
                    interes = Float.parseFloat(txbInteres.getText())*Integer.parseInt(txbCuotas.getText())*Integer.parseInt(txbMonto.getText())/5200;
                    intcap = (int)interes;
                    
                    if (i == Integer.parseInt(txbCuotas.getText())) {
                     
                    capital = Integer.parseInt(txbMonto.getText());
                  
                    intcap = Integer.parseInt(txbMonto.getText()) + (int)interes;
                    acuinter = acuinter+(int)interes;

                    jLabel14.setText(Integer.toString(intcap));
                    jLabel16.setText(Integer.toString(acuinter));
                    
                    
                    jLabel16.setVisible(true);
                    jLabel15.setVisible(true);
                    jLabel5.setVisible(true);
                    jLabel14.setVisible(true);
                    
                    
                    txbMontoPorPagos.setText(Integer.toString((int)interes));
                    txbMontoFinal.setText(txbMonto.getText());
//                    total = intcap + acuinter;
//                    txbTotal.setText(Integer.toString(total));
                        
                    
                        
                    }
                    modelo.addRow(new Object[]{i, intcap , fecha, capital , (int)interes});
                    acupagos1= capital + (int)interes;
                    acupagos = acupagos+acupagos1;
                    txbTotal.setText(Integer.toString(acupagos));
                    
                } else if (forma == 2) {
                    fechaCal.add(Calendar.MONTH, 1);
                    acuinter = acuinter+(int)interes;
                    interes = Float.parseFloat(txbInteres.getText())*Integer.parseInt(txbCuotas.getText())*Integer.parseInt(txbMonto.getText())/1200;
                    intcap = (int)interes;
                    
                    if (i == Integer.parseInt(txbCuotas.getText())) {
                     
                    capital = Integer.parseInt(txbMonto.getText());
                  
                    intcap = Integer.parseInt(txbMonto.getText()) + (int)interes;
                    acuinter = acuinter+(int)interes;

                    jLabel14.setText(Integer.toString(intcap));
                    jLabel16.setText(Integer.toString(acuinter));
                    
                    
                    jLabel16.setVisible(true);
                    jLabel15.setVisible(true);
                    
                    
                    jLabel5.setVisible(true);
                    jLabel14.setVisible(true);
                        
                    txbMontoPorPagos.setText(Integer.toString((int)interes));
                    txbMontoFinal.setText(txbMonto.getText());
//                    total = intcap + acuinter;
//                    txbTotal.setText(Integer.toString(total));
                    
                        
                    }
                    modelo.addRow(new Object[]{i, intcap , fecha, capital , (int)interes});
                    acupagos1= capital + (int)interes;
                    acupagos = acupagos+acupagos1;
                    txbTotal.setText(Integer.toString(acupagos));
                    
                } else if (forma == 3) {
                    fechaCal.add(Calendar.YEAR, 1);
                    //getInteres.getText+(getCuotas.getText/getMonto.getText)
                    acuinter = acuinter+(int)interes;
                    interes = Float.parseFloat(txbInteres.getText())*Integer.parseInt(txbCuotas.getText())*Integer.parseInt(txbMonto.getText())/100;
                    intcap = (int)interes;
                    
                    
                    
                    if (i == Integer.parseInt(txbCuotas.getText())) {
                     
                    capital = Integer.parseInt(txbMonto.getText());
                  
                    intcap = Integer.parseInt(txbMonto.getText()) + (int)interes;
                    acuinter = acuinter+(int)interes;
                    jLabel14.setText(Integer.toString(intcap));
                    jLabel16.setText(Integer.toString(acuinter));
                    
                    
                    jLabel16.setVisible(true);
                    jLabel15.setVisible(true);
                    
                    
                    jLabel5.setVisible(true);
                    jLabel14.setVisible(true);
                    
                    txbMontoPorPagos.setText(Integer.toString((int)interes));
                    txbMontoFinal.setText(txbMonto.getText());
//                    total = intcap + acuinter;
//                    txbTotal.setText(Integer.toString(total));
//                        
                    }
                    modelo.addRow(new Object[]{i, intcap , fecha, capital ,(int) interes});
                    acupagos1= capital + (int)interes;
                    acupagos = acupagos+acupagos1;
                    txbTotal.setText(Integer.toString(acupagos));
                  
                }
           

            }
                
//            fecha = fechaToString(fechaCal);
           
            

        }
        
        } catch (Exception e) {
             if (pago == 2) {
            JOptionPane.showMessageDialog(this, "No se cargaron todos los datos o se cargaron de manera equivocada", "ERROR", 2);
            
                } else if (pago == 0) {
                                JOptionPane.showMessageDialog(this, "No se cargaron todos los datos o se cargaron de manera equivocada", "ERROR", 2);

                }
             }
    
         
         
         try {
 
        for (int i = 1; i <= Integer.parseInt(this.txbCuotas.getText()); i++) {
            if (pago == 1) {
                

                if (forma == 0) {
                    JOptionPane.showMessageDialog(this, "Seleccione una forma de pago ", "ERROR", 3);
                    return;
               
                } else if (forma == 1) {
                    acuinter = acuinter + (int) interes ;
                    fechaCal.add(Calendar.WEEK_OF_YEAR, 1);
                    jLabel5.setVisible(false);
                    jLabel14.setVisible(false);
//                    acuinter = acuinter + (int) interes;
                    interes = Float.parseFloat(txbInteres.getText())*Integer.parseInt(txbCuotas.getText())*Integer.parseInt(txbMonto.getText())/5200;
                    capital1 =  Integer.parseInt(txbMonto.getText())/Integer.parseInt(txbCuotas.getText());
                    intcap = capital1 + (int)interes;
                    
//                    jLabel16.setText(Integer.toString(acuinter));
                    
                    
                    jLabel16.setVisible(true);
                    jLabel15.setVisible(true);
                    
                    
                    txbMontoPorPagos.setText(Integer.toString(intcap));
                    txbMontoFinal.setText(txbMonto.getText());
                    asd = Integer.parseInt(txbMonto.getText());
                        
                    
                    
                    modelo.addRow(new Object[]{i, intcap , fecha, capital1 , (int)interes});
                    acupagos2 = acupagos2 + intcap;
                    txbTotal.setText(Integer.toString(acupagos2));
//                    jLabel16.setText(txbMonto.getText()-Integer.toString(acupagos2) );
                    acupagos3 = acupagos2 - asd;
                    jLabel16.setText(Integer.toString(acupagos3));
                    
                } else if (forma == 2) {
                    acuinter = acuinter + (int) interes;
                    fechaCal.add(Calendar.MONTH, 1);
                    //1200
                   jLabel5.setVisible(false);
                    jLabel14.setVisible(false);
//                    acuinter = acuinter + (int) interes;
                    interes = Float.parseFloat(txbInteres.getText())*Integer.parseInt(txbCuotas.getText())*Integer.parseInt(txbMonto.getText())/1200;
                    capital1 =  Integer.parseInt(txbMonto.getText())/Integer.parseInt(txbCuotas.getText());
                    intcap = capital1 + (int)interes;
                    
//                    jLabel16.setText(Integer.toString(acuinter));
                    
                    
                    jLabel16.setVisible(true);
                    jLabel15.setVisible(true);
                    
                    
                    txbMontoPorPagos.setText(Integer.toString(intcap));
                    txbMontoFinal.setText(txbMonto.getText());
                    asd = Integer.parseInt(txbMonto.getText());
                        
                    
                    
                    modelo.addRow(new Object[]{i, intcap , fecha, capital1 , (int)interes});
                    acupagos2 = acupagos2 + intcap;
                    txbTotal.setText(Integer.toString(acupagos2));
//                    jLabel16.setText(txbMonto.getText()-Integer.toString(acupagos2) );
                    acupagos3 = acupagos2 - asd;
                    jLabel16.setText(Integer.toString(acupagos3));
                    
                } else if (forma == 3) {
                    acuinter = acuinter + (int) interes;
                    fechaCal.add(Calendar.YEAR, 1);
                    //100
                   jLabel5.setVisible(false);
                    jLabel14.setVisible(false);
//                    acuinter = acuinter + (int) interes;
                    interes = Float.parseFloat(txbInteres.getText())*Integer.parseInt(txbCuotas.getText())*Integer.parseInt(txbMonto.getText())/100;
                    capital1 =  Integer.parseInt(txbMonto.getText())/Integer.parseInt(txbCuotas.getText());
                    intcap = capital1 + (int)interes;
                    
//                    jLabel16.setText(Integer.toString(acuinter));
                    
                    
                    jLabel16.setVisible(true);
                    jLabel15.setVisible(true);
                    
                    
                    txbMontoPorPagos.setText(Integer.toString(intcap));
                    txbMontoFinal.setText(txbMonto.getText());
                    asd = Integer.parseInt(txbMonto.getText());
                        
                    
                    
                    modelo.addRow(new Object[]{i, intcap , fecha, capital1 , (int)interes});
                    acupagos2 = acupagos2 + intcap;
                    txbTotal.setText(Integer.toString(acupagos2));
//                    jLabel16.setText(txbMonto.getText()-Integer.toString(acupagos2) );
                    acupagos3 = acupagos2 - asd;
                    jLabel16.setText(Integer.toString(acupagos3));
                }
           

            }
                
            fecha = fechaToString(fechaCal);
            
            
            

        }
        
        } catch (Exception e) {
            if (pago == 1) {
            
            JOptionPane.showMessageDialog(this, "No se cargaron todos los datos o se cargaron de manera equivocada", "ERROR", 2);
                }
            }


    }//GEN-LAST:event_btnCalcularActionPerformed
    private void addElemento(String[] elemento) {

    }

    private String fechaToString(Calendar cal) {
        String fecha = "" + cal.get(Calendar.DAY_OF_MONTH) + "/"
                + (cal.get(Calendar.MONTH) + 1) + "/"
                + cal.get(Calendar.YEAR);
        return fecha;
    }

    private void jDateChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDateChooser1MouseClicked

    }//GEN-LAST:event_jDateChooser1MouseClicked

    private void txbInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbInteresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbInteresActionPerformed

    private void txbMontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txbMontoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbMontoKeyPressed

    private void txbMontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txbMontoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txbMontoFocusGained

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:

            jTable1.print(JTable.PrintMode.NORMAL, null, null, true, null, true, null);
        } catch (PrinterException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (HeadlessException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Proyecto hecho por NICOLAS SANCHEZ \n Nota: \n -La primer cuota de todo prestamo se paga en el momento de la acreditacion de dicho prestamo.\n -Al exportar, la tabla esta se guarda en su carpeta personal / PDF", "Info", 1);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        txbMonto.setText(null);
        txbCuotas.setText(null);
        txbInteres.setText(null);
        txbMontoFinal.setText(null);
        txbMontoPorPagos.setText(null);
        txbTotal.setText(null);
        cmbFormadepago.setSelectedIndex(0);
        cmbMetodo.setSelectedIndex(0);
        jLabel5.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model.setNumRows(0);
      //  for (int i =0;i<;i++){
      //      model.removeRow(i);
       // }
        jTable1.setModel(model);
        //jTable1.setModel(new DefaultTableModel());
        
      
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
                System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
//    
//    private class ManejadorTecla implements KeyListener{
//public void keyPressed(KeyEvent e) {
//if(e.getKeyCode()==KeyEvent.VK_ENTER){
//Robot Tecla = null;
//try {
//Tecla = new Robot();
//} catch (AWTException e1) {
//e1.printStackTrace();
//}
//Tecla.keyPress(KeyEvent.VK_TAB);
//}
//}
//public void keyReleased(KeyEvent arg0) {}
//public void keyTyped(KeyEvent arg0) {}
//ManejadorTecla manejador = new ManejadorTecla();



    
//}//Fin de la clase privada ManejadorTecla()

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JComboBox cmbFormadepago;
    private javax.swing.JComboBox cmbMetodo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txbCuotas;
    private javax.swing.JTextField txbInteres;
    private javax.swing.JTextField txbMonto;
    private javax.swing.JTextField txbMontoFinal;
    private javax.swing.JTextField txbMontoPorPagos;
    private javax.swing.JTextField txbTotal;
    // End of variables declaration//GEN-END:variables
}
